#!/usr/bin/env python3

import rospy
from sensor_msgs.msg import JointState
from std_msgs.msg import Float64MultiArray


class JointStatesToFloat:
    def __init__(self, namespace):
        self.rate = rospy.Rate(10)
        self.msg_received = False
        self.joint_state_msg = None
        self.previous_angles = []
        rospy.Subscriber('fake_joint_states', JointState, self.JointStatesCB)
        rospy.loginfo('waiting for first joint state msg to be published')
        self.wait_for_first_msg()
        rospy.loginfo('joint state msg received, proceeding')
        # init previous angle list
        self.previous_angles = [0] * len(self.joint_state_msg.position)
        # create one publisher
        self.pub = rospy.Publisher(namespace + 'position_controller/command', Float64MultiArray, queue_size=1)

    def wait_for_first_msg(self):
        while not self.msg_received:
            # wait until at least one joint state msg is received
            self.rate.sleep()

    def JointStatesCB(self, msg):
        self.joint_state_msg = msg
        self.msg_received = True

    def publishJointsAsFloats(self):
        # extract desired angles from joint state msg
        angles = [a for a in self.joint_state_msg.position]
        # compare previous angles to see if there was any change
        changes = []
        for i, previous_angle in enumerate(self.previous_angles):
            changes.append(previous_angle != angles[i])
        # publish desired angles to float topic
        if any(changes):
            float_msg = Float64MultiArray()
            float_msg.data = angles
            self.pub.publish(float_msg)
        # to keep track if the angle changed or not
        self.previous_angles = angles

    def start(self):
        while not rospy.is_shutdown():
            if self.msg_received:
                # lower flag
                self.msg_received = False
                self.publishJointsAsFloats()
            self.rate.sleep()


if __name__ == '__main__':
    rospy.init_node('joint_states_to_float', anonymous=False)
    jstf = JointStatesToFloat(rospy.get_namespace())
    jstf.start()
