# pybullet plugins, will be loaded during runtime
plugins:
  - module: pybullet_ros.plugins.control
    class: Control
  - module: pybullet_ros.plugins.joint_state_pub
    class: joinStatePub
  - module: pybullet_ros.plugins.rgbd_camera
    class: RGBDCamera

loop_rate:              80.0
gravity:                -9.81
max_effort:             5000.0
use_intertia_from_file: False

rgbd_camera:
    frame_id:           tip_link
    resolution:
        width:          640
        height:         480

robots:
  - acrobat
