# pybullet plugins, will be loaded during runtime
# -----------------------------------------------------------------------
# control  - Position, velocity and effort control for all joints on the robot
# joint_state_pub - Query robot state and publish position, velocity and effort values to /robot_name/joint_states
plugins:
  - module: pybullet_ros.plugins.control
    class: Control
  - module: pybullet_ros.plugins.joint_state_pub
    class: jointStatePub

loop_rate: 500.0 # the frequency at which to step sim in h
gravity: -9.81 # earth gravity in m/s^2
max_effort: 100.0 # the max force to apply to the robot joints in vel mode

# True = allow pybullet to compute the inertia tensor based on mass and volume of the collision shape
# False = you can provide a more accurate inertia tensor, so inertia will be read then from URDF model
use_intertia_from_file: False

# robot names
robots:
  - franka
